<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cadfe30b-93b1-46f2-9164-64f1ad3d7fae</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.col-md-8</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'col-md-8 col-lg-9')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>col-md-8 col-lg-9</value>
        <webElementGuid>cf7279f5-7e4a-4872-991e-164bb670bb75</webElementGuid>
    </webElementProperties>
</WebElementEntity>