<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bd0ed3ef-9d3e-40cb-94da-0a83ecacff5c</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.mars-logo-row__container</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'container-xxl mars-logo-row__container')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>container-xxl mars-logo-row__container</value>
        <webElementGuid>644d6389-a32c-45c6-8e04-aec07036aba2</webElementGuid>
    </webElementProperties>
</WebElementEntity>